### ISSUE TITLE
it would be nice if task name only needed to be specified once

### ISSUE THREAD

**Issue by iambumblehead** [jakebailey/hereby#105]
Probably there are reasons 'build' must declare twice (the exported name and again at the `name` property.)  Feel free to close this issue as just a casual suggestion...
```javascript
export const build = task({
    name: "build",
    run: async () => {
        await execa("tsc", ["-b", "./src"]);
    },
})
```

Imo it would be cool if something like this could be used instead,
```javascript
export default [
  task({
    name: "build",
    run: async () => {
        await execa("tsc", ["-b", "./src"]);
    }
  })
]
```

Two reasons the latter pattern could be preferred,
 1. the task name is defined in one place and one way only,
 2. allows task name to more-easily be used as a variable name used by the task

The named-variables reason of point 2 is difficult to explain, however the below example would be easier to do using the suggested interface, because 'buildsitemap' is more easily imported to 'buildsitemap' while being simultaneously used as a task name 'buildsitemap',
```javascript
import buildsitemap from './buildsitemap.js'

export default [
  task({
    name: 'buildsitemap',
    run: async () => {
        await buildsitemap()
  })
]
```

thanks for hereby.js and regards :)

**Comment by jakebailey** [comment]
I don't think I would allow exporting an array; `export default` is explicitly used for specifying which task should run when `hereby` is not given a task name.

However, I have a change locally that I never pushed which does something like this but from the other direction; it allows you to omit the name in the object and infer it from the export name, so long as there's only one export of it (besides `default`). Perhaps that would be helpful?

(If so, the so long my 500 LoC 😄)

**Comment by jakebailey** [comment]
Also, out of curiousity, where are you using `hereby`?

**Comment by iambumblehead** [comment]
Thanks for the reply.

> Also, out of curiousity, where are you using hereby?

I'm using hereby in something I've been developing solo for awhile and it may never see a public release.
