### ISSUE TITLE
another feature that would be nice to have and possible issue surfacing errors

### ISSUE THREAD

**Issue by iambumblehead** [jakebailey/hereby#110]
it would also be nice if Hereby could load an external file such as like this,
```javascript
export const build = task({
  name: "esbuild",
  run: "./esbuild.js"
})
```

sometimes its useful configure build scripts outside of hereby.js, eg `node ./esbuild.js` vs `hereby esbuild` and currently need to do something like this,
_esbuild.js_
```javascript
const esbuild = () => { /* ... */ }

// temporary condition; run script directly if not called through hereby,
if (!process.argv.find(arg => /hereby\.js$/.test(arg))) {
  await esbuild()
}

export default esbuild
```

Additionally, it appears hereby does not surface errors in a useful way. For example, if a runtime error occurs in the 'esbuild' task, there is no stack trace and one must call `node ./esbuild.js` directly to get a full stack trace.

**Comment by jakebailey** [comment]
A `Herebyfile` is just a module already; can you just import what you need from another file?

```js
export const build = task({
  name: "esbuild",
  run: () => import("./esbuild.js"),
})
```

**Comment by jakebailey** [comment]
Though it sure seems like at that point you could forego the argv thing and just do:

```js
  name: "esbuild",
  run: async () => {
    const esbuild = (await import("./esbuild.js")).default;
	return esbuild();
  },
})
```

**Comment by iambumblehead** [comment]
oh thanks, you're right! why didn't I think of that?

**Comment by jakebailey** [comment]
Yeah, importing from other places is the canonical way to do things. You can even reexport other files' `task`s, though there's still only one set of names so they must be unique. I have considered adding in the idea of a task "namespace" such that one can split up files, but it so far has not seemed needed by anyone.
