### ISSUE TITLE
It's called hereby, don't use it, thanks -- Why?

### ISSUE THREAD

**Issue by Gerrit0** [jakebailey/hereby#36]
In the [talk-ts-congress-2023](https://github.com/jakebailey/talk-ts-congress-2023/blob/main/slides.md#complete-build-overhaul) slides, there is a line:

> It's called hereby, don't use it, thanks 😅

Could I ask why? TypeDoc's build system has become somewhat messy, and I liked the way this looked last time I looked at the TS compiler's build setup...

**Comment by jakebailey** [comment]
This package was intended for use in TypeScript's build system, and that's basically it. It has all of the features it needs, and it's unlikely I'm going to add any more. If you're happy with those warnings, then feel free to use it!

That line was more of a joke; I'm not one to advertise my projects, so at best I can try to be funny about it.
