### ISSUE TITLE
feature request: support for node's --env-file args

### ISSUE THREAD

**Issue by iambumblehead** [jakebailey/hereby#39]
Thanks for hereby. It is an awesome small package and the best task runner I have used.

Currently, using --env-file with hereby is a little verbose,
```bash
hereby --env-file=.env test # does not load env file
node --env-file=.env node_modules/hereby/bin/hereby.js test # does load env file
```
It would be nice if there were a streamlined way to send an env file into the hereby process 

https://nodejs.org/dist/latest-v20.x/docs/api/cli.html#--env-fileconfig

**Comment by jakebailey** [comment]
> Thanks for hereby. It is an awesome small package and the best task runner I have used.

Thank you! ❤️ 

> It would be nice if there were a streamlined way to send an env file into the hereby process

Truthfully, I'm not sure how to do that; by the time `hereby` is running, Node's flags are already processed, and Node doesn't offer the code behind `--env-file` programmatically (it's implemented in C++). I'd have to reexec another process to pass those flags in, or, take a dependency on a different lib like `dotenv`, which I'd prefer not to do.

It may be easier to just do something like `env-cmd hereby`, which would auto-load `.env` and run any command; I honestly expect every Node CLI to have this problem...

**Comment by iambumblehead** [comment]
understood, thanks :)
