### ISSUE TITLE
Detect script name when use `npm run`

### ISSUE THREAD

**Issue by bytemain** [jakebailey/hereby#74]
when user run script by `npm run`(or yarn/pnpm), there is a env indicate that which script is running:

```
process.env.npm_lifecycle_event
```

if we can use this arg, user can simplify there usage:

from:
```json
"build:libs": "hereby build:libs",
"build:node": "hereby build:node",
"dev": "hereby dev",
```

to:
```json
"build:libs": "hereby",
"build:node": "hereby",
"dev": "hereby",
```

currrently if user who simply run `hereby`, we we find the default task and run.
so if user don't export a default task , we can enable this feature for him

**Comment by jakebailey** [comment]
That's a cool trick, but I don't think I want to implement it, sorry.

This adds complexity and makes it more difficult to reason about what task `hereby` will run. It would also break anyone who is relying on the default task in existing scripts, and potentially those indirectly executing hereby from another script (as the environment will be passed down to child processes).

You are free to write a wrapper script that can perform this translation, if so desired. It should only come out to be a couple of lines, like `process.argv.splice(2, 0, process.env.npm_lifecycle_event)`.

**Comment by bytemain** [comment]
Thanks for you reply, now I will write a wrapper script that can perform this translation in my project.

**Comment by bytemain** [comment]
Here is a simple wrapper make this work.

```ts
// Herebyfile.mjs
export default task({
  name: 'default',
  run: async () => {
    if (process.env.npm_lifecycle_event === undefined) {
      throw new Error('No script specified');
    }

    await execa('hereby', [process.env.npm_lifecycle_event], {
      stdio: 'inherit',
    });
  },
});

```
